#!/bin/bash

# Flutter Mobile App Development Environment Setup Script
# For InamiMapApp V4.1

set -e

echo "🚀 Setting up Flutter development environment for InamiMapApp..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running on macOS
if [[ "$OSTYPE" != "darwin"* ]]; then
    print_error "This script is designed for macOS only"
    exit 1
fi

print_status "Checking system requirements..."

# Check Homebrew
if ! command -v brew &> /dev/null; then
    print_status "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    print_success "Homebrew already installed"
fi

# Update Homebrew
print_status "Updating Homebrew..."
brew update

# Install Flutter
if ! command -v flutter &> /dev/null; then
    print_status "Installing Flutter..."
    brew install --cask flutter
else
    print_success "Flutter already installed"
fi

# Add Flutter to PATH if not already there
if [[ ":$PATH:" != *":/opt/homebrew/bin:"* ]]; then
    echo 'export PATH="/opt/homebrew/bin:$PATH"' >> ~/.zshrc
    export PATH="/opt/homebrew/bin:$PATH"
fi

# Install Android Studio (for Android development)
if ! ls /Applications/ | grep -q "Android Studio"; then
    print_status "Installing Android Studio..."
    brew install --cask android-studio
else
    print_success "Android Studio already installed"
fi

# Install Xcode (for iOS development) - this needs to be done manually from App Store
if ! ls /Applications/ | grep -q "Xcode.app"; then
    print_warning "Xcode not found. Please install Xcode from the App Store manually."
    print_warning "After installing Xcode, run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer"
else
    print_success "Xcode already installed"
    # Ensure Xcode command line tools are properly configured
    sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
fi

# Install CocoaPods for iOS dependencies
if ! command -v pod &> /dev/null; then
    print_status "Installing CocoaPods..."
    sudo gem install cocoapods
else
    print_success "CocoaPods already installed"
fi

# Install additional tools
print_status "Installing additional development tools..."
brew install git
brew install node

# Run Flutter doctor to check setup
print_status "Running Flutter doctor to check setup..."
flutter doctor

print_success "Development environment setup completed!"
print_status "Next steps:"
echo "1. Accept Android licenses: flutter doctor --android-licenses"
echo "2. Install Xcode from App Store if not already installed"
echo "3. Configure Firebase for both platforms"
echo "4. Run 'flutter doctor' again to verify all issues are resolved"

# Create Android local.properties file placeholder
mkdir -p android
cat > android/local.properties << EOF
# Android SDK location
# This file should be automatically generated by Android Studio
# If you need to set it manually, uncomment and modify the line below:
# sdk.dir=/Users/$(whoami)/Library/Android/sdk
EOF

print_status "Created android/local.properties placeholder"
print_warning "You'll need to configure the Android SDK path after installing Android Studio"